# Generated by Django 3.2.4 on 2021-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_where', models.CharField(max_length=255, verbose_name='Откуда')),
                ('where', models.CharField(max_length=255, verbose_name='Куда')),
                ('date', models.DateField(verbose_name='Когда')),
                ('car', models.CharField(max_length=255, verbose_name='Машина')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_where', models.CharField(max_length=255, verbose_name='Откуда')),
                ('where', models.CharField(max_length=255, verbose_name='Куда')),
                ('date', models.DateField(verbose_name='Когда')),
                ('passengers', models.CharField(max_length=10, verbose_name='Пассажир')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
    ]
